FROM oven/bun:1 as builder

WORKDIR /app

COPY ./package.json /app/package.json
COPY ./packages /app/packages
COPY ./bun.lock /app/bun.lock
COPY ./turbo.json /app/turbo.json

COPY ./apps/ws-backend /app/apps/ws-backend

RUN bun install
RUN bun run db:generate

CMD ["bun","run","start:ws-backend"]